<?php

use SocolaDaiCa\LaravelModulesCommand\Constants\License;

return [
    /*
    |--------------------------------------------------------------------------
    | Module Namespace
    |--------------------------------------------------------------------------
    |
    | Default module namespace.
    |
    */
    'namespace' => 'SocolaDaiCa',

    /*
    |--------------------------------------------------------------------------
    | Composer File Template
    |--------------------------------------------------------------------------
    |
    | Here is the config for composer.json file, generated by this package
    |
    */

    'composer' => [
        // 'vendor' => 'socoladaica',
        'vendor' => 'licence528',
        'php' => '^8.1',
        'license' => License::MIT,
        'author' => [
            'name' => 'Socola Đại Ca',
            'email' => 'SocolaDaiCa@gmail.com',
            'role' => 'Developer',
            'homepage' => 'https://github.com/SocolaDaiCa',
        ],
        'composer-output' => false,
    ],
];
