# https://github.com/marketplace/actions/automatic-releases

name: "Release"

on:
  push:
    branches:
      - "[0-9]+.x"
      - "socoladaica"

jobs:
  release:
    uses: SocolarDaiCa/.github/.github/workflows/release.yml@1.x
    with:
      version: $GITHUB_REF
